### ISSUE TITLE
Workaround to install it

### ISSUE THREAD

**Issue by Jexxio** [fcturner/sharerenamer#1]
Nice job, guys, really nice job!
Altough there's a little problem when enabling this app.

Trying to enable it in WebGUI said it couldn't find the app name, this is due to the containing folder is named `share_renamer` and the installer look fors `sharerenamer`, figured it out a bit later by reading the config files.
So, the solution is either to modify the config files or just to rename the app containing folder, i think the second one is a better option.

**Comment by fcturner** [comment]
I'm only alone :smile: 

Thanks for you reply, I'll look into this.

**Comment by Jexxio** [comment]
Then, @fcturner, you're a badass! nice job

**Comment by fcturner** [comment]
Fixed!
