### ISSUE TITLE
App doesn't work after upgrading OC to 9.1.4 (stable)

### ISSUE THREAD

**Issue by tedstrauss** [fcturner/sharerenamer#14]
The app worked fine before upgrade.
Now it doesn't work and when i try to re-enable in the app interface, get error:
`Archives of type text/html are not supported`

Is there any way to manually install in the back end?

**Comment by fcturner** [comment]
Sure!

#### Package download
(remember to rename the folder to `sharerenamer`)
[:package:ZIP file](../archive/master.zip)
[:package:TAR file](../archive/master.tar.gz)

#### Command line (even easier)
(assuming `/var/www/owncloud/` as your root location)
 ```sh
rm -rf /var/www/owncloud/apps/sharerenamer
git clone https://github.com/fcturner/sharerenamer.git /var/www/owncloud/apps/sharerenamer
```

**Comment by tedstrauss** [comment]
After following above steps, I get: `Error: could not disable broken app`
in the apps interface, when trying to enable the app.
:(

**Comment by fcturner** [comment]
Are you sure the folders are all set as they should be? I've never seen this error. Are you trying to disable it? You could run occ:upgrade:
https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/occ_command.html

**Comment by tedstrauss** [comment]
on a guess, I ran `delete from oc_appconfig where appid="sharerenamer";` in the DB to clean up leftover DB entry. After this, I was able to enable the app, and it now works. 
Thanks!

**Comment by fcturner** [comment]
You're welcome!
