### ISSUE TITLE
Deleted file

### ISSUE THREAD

**Issue by Atisom** [fcturner/sharerenamer#4]
I deleted a file without take back the share, then I cannot reuse this URL

**Comment by fcturner** [comment]
Hello!

Unfortunately, I don't have a clue what you mean.
Or do you mean, you:
  1. Shared a file
  2. Renamed the link using my app
  3. Deleted the share
  4. Shared the file again, by clinking on 'Share link' again

And then you are surprised that the new link doesn't has the share name you created in step 2?
If that's the case, I cannot change that behaviour. You basically removed the share totally from the database and by so, your new share name. If you would do this even *without* renaming the share (step 2), you would end up with another link too.

I cannot check for historical share links, as the are removed instantly from the database and recreated with a totally different share link.

**Comment by fcturner** [comment]
Wait, am I getting this right? Is that what you meant?

**Comment by fcturner** [comment]
Guess so.
