### ISSUE TITLE
Just nothing happens

### ISSUE THREAD

**Issue by 466** [fcturner/sharerenamer#5]
Hi there,
i installed the app via git cloning into my apps folder, sadly this did not change anything, there is no button for me to rename the link.
Even without an adblocker, any ideas?

**Comment by fcturner** [comment]
Did you enable the app as admin?

**Comment by 466** [comment]
....
well, yeha, good idea :)
I must haved mixed up 2 installations, enabling on the correct one, with an up to date git tree, link renaming works, thanks!

**Comment by fcturner** [comment]
👍
