### ISSUE TITLE
"Archives of type text/html are not supported"

### ISSUE THREAD

**Issue by ThongSong7** [fcturner/sharerenamer#6]
Would love to see this working on my build.  
NextCloud 10.0.1 Stable, Debian 8

Is this something on MY side or Yours?  When enabling it from the NextCloud Apps Store I get the message above.  If the prior, any suggestions?  Thanks in advance!

Cheers.

**Comment by fcturner** [comment]
Just no support for app stores, I like my privacy. 

You can download the latest master and put it in your apps folder, rename it to sharerenamer. You'll be good to go! :wink:

**Comment by ThongSong7** [comment]
Thanks, that did it.
