### ISSUE TITLE
Cancel Button is not showing and rename buttom is redering outside of screen viewing area.

### ISSUE THREAD

**Issue by JarbyDev** [fcturner/sharerenamer#7]
Cancel Button is not showing and rename button is rendering outside of screen viewing area.
also the copy llink button is is moving to underneath of rename button

![rename](https://cloud.githubusercontent.com/assets/11229573/20240076/609c0f1c-a8dd-11e6-803c-ee2370497e38.PNG)

**Comment by fcturner** [comment]
Thanks! I'll fix this next week.

**Comment by fcturner** [comment]
This should now be fixed in the latest master.
 * Package download
  * [:package:ZIP file](../archive/master.zip)
  * [:package:TAR file](../archive/master.tar.gz)
 * Command line (assuming `/var/www/owncloud/` as your root location)

 ```sh
rm -rf /var/www/owncloud/apps/sharerenamer
git clone https://github.com/fcturner/sharerenamer.git /var/www/owncloud/apps/sharerenamer
```
